sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer self-update
  - mkdir -p tests/build/logs

script:
  - composer require dasprid/container-interop-doctrine:^1.1 --prefer-source $PREFER_LOWEST
  - cp tests/TestConfigurationContainerInteropDoctrine.php.dist tests/TestConfiguration.php.dist
  - vendor/bin/phpunit -c ./phpunit.xml.dist
  - composer remove dasprid/container-interop-doctrine
  - rm tests/TestConfiguration.php.dist
  - git checkout HEAD composer.json && rm -Rf vendor && rm composer.lock
  - composer require doctrine/doctrine-orm-module:"~0.7||^1.0||^2.1" --prefer-source $PREFER_LOWEST
  - cp tests/TestConfigurationDoctrineORMModule.php.dist tests/TestConfiguration.php.dist
  - vendor/bin/phpunit -c ./phpunit.xml.dist
  - vendor/bin/phpcs --standard=PSR2 src

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
